apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bringg-k8s-local-all-in-one
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nikolay-udovik/bringg-k8s-monorepo.git'
    path: kubernetes/argocd/local
    targetRevision: HEAD 
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true