---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps-helm
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: argocd
            chartRepoURL: 'https://argoproj.github.io/argo-helm'
            chartName: argo-cd
            chartVersion: 7.2.1
            valuesPath: kubernetes/apps/infra/argocd/local/values.yaml
            valuesPathDir: kubernetes/apps/infra/argocd/local
            destinationServer: "https://kubernetes.default.svc"
            destinationNamespace: argocd

          - name: prometheus-stack
            chartRepoURL: 'https://prometheus-community.github.io/helm-charts'
            chartName: kube-prometheus-stack
            chartVersion: 67.5.0
            valuesPath: kubernetes/apps/infra/monitoring/kube-prometheus-stack/local/values.yaml
            valuesPathDir: kubernetes/apps/infra/monitoring/kube-prometheus-stack/local
            destinationServer: "https://kubernetes.default.svc"
            destinationNamespace: monitoring

          - name: metrics-server
            chartRepoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
            chartName: metrics-server
            chartVersion: 3.12.2
            valuesPath: kubernetes/apps/infra/kube-system/metrics-server/local/values.yaml
            valuesPathDir: kubernetes/apps/infra/kube-system/metrics-server/local
            destinationServer: "https://kubernetes.default.svc"
            destinationNamespace: kube-system

          - name: keda
            chartRepoURL: 'https://kedacore.github.io/charts'
            chartName: keda
            chartVersion: 2.16.1
            valuesPath: kubernetes/apps/infra/keda/local/values.yaml
            valuesPathDir: kubernetes/apps/infra/keda/local
            destinationServer: "https://kubernetes.default.svc"
            destinationNamespace: keda
  template:
    metadata:
      name: '{{name}}'
      labels:
        environment: local
        app-type: infra
    spec:
      project: default
      sources:
        - repoURL: '{{chartRepoURL}}'
          targetRevision: '{{chartVersion}}'
          chart: '{{chartName}}'
          helm:
            valueFiles:
              - '$values/{{valuesPath}}'
        - repoURL: 'https://github.com/nikolay-udovik/bringg-k8s-monorepo.git'
          targetRevision: master
          path: '{{valuesPathDir}}'
          ref: values
      destination:
        server: '{{destinationServer}}'
        namespace: '{{destinationNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  labels:
    environment: local
    app-type: infra
spec:
  project: default
  source:
    repoURL: 'https://github.com/kubernetes/ingress-nginx.git'
    targetRevision: HEAD
    path: deploy/static/provider/kind
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipSchemaValidation=true
