---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-backend
  namespace: argocd
  labels:
    environment: local
    app-type: workloads
spec:
  project: default
  sources:
  - repoURL: 'https://stefanprodan.github.io/podinfo'
    targetRevision: '6.7.1'
    chart: podinfo
    helm:
      valueFiles:
        - $values/kubernetes/apps/workloads/demo/podinfo-back/local/values.yaml
    path: kubernetes/apps/workloads/demo/podinfo-back/local
  - repoURL: 'https://github.com/nikolay-udovik/bringg-k8s-monorepo.git'
    targetRevision: master
    path: kubernetes/apps/workloads/demo/podinfo-back/local
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-front
  namespace: argocd
  labels:
    environment: local
    app-type: workloads
spec:
  project: default
  sources:
  - repoURL: 'https://stefanprodan.github.io/podinfo'
    targetRevision: '6.7.1'
    chart: podinfo
    helm:
      valueFiles:
        - $values/kubernetes/apps/workloads/demo/podinfo-front/local/values.yaml
    path: kubernetes/apps/workloads/demo/podinfo-front/local
  - repoURL: 'https://github.com/nikolay-udovik/bringg-k8s-monorepo.git'
    targetRevision: master
    path: kubernetes/apps/workloads/demo/podinfo-front/local
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-validator
  namespace: argocd
  labels:
    environment: local
    app-type: workloads
spec:
  project: default
  source:
    repoURL: 'https://github.com/nikolay-udovik/bringg-podinfo-token-validator.git'
    targetRevision: master
    path: kubernetes/overlays/local
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true