apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: podinfo-back-scaledobject
  namespace: demo 
spec:
  scaleTargetRef:
    name: podinfo-backend  # Update this to your target deployment name
  pollingInterval: 2
  cooldownPeriod: 5
  minReplicaCount: 2   
  maxReplicaCount: 10  
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "80"