crds:
  enabled: true

cleanPrometheusOperatorObjectNames: true

alertmanager:
  ingress:
    enabled: false

prometheus:
  externalUrl: http://localhost/prometheus
  ingress:
    enabled: true
    ingressClassName: nginx
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
    - paths:
      - path: /prometheus(/|$)(.*)
        backend:
          serviceName: prometheus-server
          servicePort: 9090

grafana:
  enabled: true
  forceDeployDashboards: true
  adminPassword: Aa123456
  externalUrl: http://localhost/grafana
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - paths:
          - path: /grafana(/|$)(.*)
            backend:
              serviceName: grafana
              servicePort: 3000
